### ISSUE TITLE
Convert the entire apparatus to YUV color space

### ISSUE THREAD

**Issue by TimothyGu** [ethanlee16/JWebcam#1]
RIght now the image from the webcam (in YUV colorspace) is forced to be converted to RGB, then being processed, then converted back to YUV to be displayed. This is extremely inefficient, especially for HD webcams.

**Comment by ethanlee16** [comment]
Thanks for this, but that would actually be more inefficient: first of all, Java doesn't support a YUV colorspace for [BufferedImage](http://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html). To work around this, I would have to use more resources creating ColorSpace objects to process it.

The reason I would have to process it is because the image from the webcam _doesn't_ come in YUV but as an OpenCV matrix from [VideoCapture with BGR channels by default](http://docs.opencv.org/modules/highgui/doc/reading_and_writing_images_and_video.html?highlight=videocapture#VideoCapture). BufferedImage's [getRGB()](http://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html#getRGB%28int,%20int%29) method takes care of color conversion from BGR to RGB for me in the Filter class.

**Comment by TimothyGu** [comment]
@ethanlee16 said:

> Thanks for this, but that would actually be more inefficient: first of all, Java doesn't support a YUV colorspace for BufferedImage. To work around this, I would have to use more resources creating ColorSpace objects to process it.
> 
> BufferedImage's getRGB() method takes care of color conversion from BGR to RGB for me in the Filter class.

```
OCV is dumb.
Dumby dumby dumb --
Too dumb.
```
